[package]
name = "game"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.16.0"

[dev-dependencies]
snforge_std = "0.57.0"
assert_macros = "2.16.0"



[[target.starknet-contract]]
sierra = true

[[target.starknet-contract]]
name = "erc20"
kind = "starknet-contract"
path = "src/erc20.cairo"
sierra = true

[[target.starknet-contract]]
name = "launchpad"
kind = "starknet-contract"
path = "src/launchpad.cairo"
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

# Visit https://foundry-rs.github.io/starknet-foundry/appendix/scarb-toml.html for more information

[tool.snforge]

[[tool.snforge.fork]]
name = "mainnet"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_10/_5S7tSyp-pRnFg3J8gpIQ"
block_id.tag = "latest"

# [[tool.snforge.fork]]                                      # Used for fork testing
# name = "SOME_NAME"                                         # Fork name
# url = "http://your.rpc.url"                                # Url of the RPC provider
# block_id.tag = "latest"                                    # Block to fork from (block tag)

# [[tool.snforge.fork]]
# name = "SOME_SECOND_NAME"
# url = "http://your.second.rpc.url"                         
# block_id.number = "123"                                    # Block to fork from (block number)

# [[tool.snforge.fork]]
# name = "SOME_THIRD_NAME"
# url = "http://your.third.rpc.url"
# block_id.hash = "0x123"                                    # Block to fork from (block hash)

# [profile.dev.cairo]                                        # Configure Cairo compiler
# unstable-add-statements-code-locations-debug-info = true   # Should be used if you want to use coverage
# unstable-add-statements-functions-debug-info = true        # Should be used if you want to use coverage/profiler
# inlining-strategy = "avoid"                                # Should be used if you want to use coverage

# [features]                                                 # Used for conditional compilation
# enable_for_tests = []                                      # Feature name and list of other features that should be enabled with it
